---

- name: Install haproxy
  ansible.builtin.apt:
    name: "{{ haproxy_package }}"
    policy_rc_d: 101
    state: present

- name: Install haproxy_extra_packages
  ansible.builtin.apt:
    name: "{{ haproxy_extra_packages }}"
    state: present

- name: Create /etc/default/haproxy
  ansible.builtin.template:
    src: Debian.default.j2
    dest: "/etc/default/haproxy"
    mode: "0644"
  notify:
    - Restart haproxy

- name: Enable haproxy_service
  ansible.builtin.service:
    name: "{{ haproxy_service }}"
    enabled: yes
