---
# tasks file for ansible-role-haproxy

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ haproxy_log_dir }}"
    mode: 0755
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    state: directory
  notify: Restart haproxy

- name: Create db directory
  file:
    path: "{{ haproxy_db_dir }}"
    mode: 0755
    owner: "{{ haproxy_user }}"
    group: "{{ haproxy_group }}"
    state: directory
  notify: Restart haproxy

- name: Create haproxy.conf
  template:
    src: haproxy.conf.j2
    dest: "{{ haproxy_conf_file }}"
    validate: echo %s
  notify: Restart haproxy

- name: Start haproxy
  service:
    name: "{{ haproxy_service }}"
    enabled: true
    state: started
