---
# tasks file for ansible-role-haproxy

- name: "Include {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Include trombik.x509_certificate
  include_role:
    name: trombik.x509_certificate
  vars:
    x509_certificate: "{{ haproxy_x509_certificate }}"
    x509_certificate_debug_log: "{{ haproxy_x509_certificate_debug_log }}"
  when:
    - haproxy_x509_certificate_enable

- name: Create haproxy.conf
  ansible.builtin.template:
    src: haproxy.conf.j2
    dest: "{{ haproxy_conf_file }}"
    validate: haproxy -c -f %s
    mode: "0644"
  notify: Restart haproxy

- name: Start haproxy
  ansible.builtin.service:
    name: "{{ haproxy_service }}"
    state: started
