---
# tasks file for ansible-role-haproxy

- name: "Include {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Create haproxy.conf
  ansible.builtin.template:
    src: haproxy.conf.j2
    dest: "{{ haproxy_conf_file }}"
    validate: haproxy -c -f %s
    mode: "0644"
  notify: Restart haproxy

- name: Start haproxy
  ansible.builtin.service:
    name: "{{ haproxy_service }}"
    state: started
